server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /user-api/ {
        proxy_pass http://api-gateway:8080/user-api/;
    }

    location /delivery-api/ {
        proxy_pass http://api-gateway:8080/delivery-api/;
    }

    location /order-api/ {
        proxy_pass http://api-gateway:8080/order-api/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
