server:
  port: 8085

spring:
  application:
    name: delivery-service
  cache:
    type: redis
    redis:
      time-to-live: 90s
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:500ms}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: delivery-service-v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: java.util.LinkedHashMap
        spring.json.trusted.packages: java.util
    listener:
      ack-mode: record
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: ${DELIVERY_SERVICE_DB_URL:jdbc:mysql://localhost:3310/delivery_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DELIVERY_SERVICE_DB_USERNAME:delivery_service}
    password: ${DELIVERY_SERVICE_DB_PASSWORD:delivery_service_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ${JWT_SECRET:c3ByaW5nLWJvb3QtdXNlci1zZXJ2aWNlLWxvY2FsLWRldmVsb3BtZW50LXNlY3JldC0yMDI2}

app:
  kafka:
    retry:
      max-attempts: 3
      backoff-ms: 1000
    topics:
      order-events: order.events.v1
      delivery-events: delivery.events.v1
