server:
  port: ${PORT:8083}

spring:
  cache:
    type: redis
    redis:
      time-to-live: 2m
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:500ms}
  application:
    name: food-catalogue-service
  datasource:
    url: ${FOOD_CATALOGUE_SERVICE_DB_URL:jdbc:mysql://localhost:3309/food_catalogue_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${FOOD_CATALOGUE_SERVICE_DB_USERNAME:food_catalogue_service}
    password: ${FOOD_CATALOGUE_SERVICE_DB_PASSWORD:food_catalogue_service_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ${JWT_SECRET:c3ByaW5nLWJvb3QtdXNlci1zZXJ2aWNlLWxvY2FsLWRldmVsb3BtZW50LXNlY3JldC0yMDI2}
